language: node_js
node_js:
  - lts/*

cache:
  directories:
    - node_modules

script:
  - npm run generate

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: .output/public
  on:
    branch: main
