name: Merging & Sending (Docker update and SSH.)

on:
  push:
    branches: ["main"]

jobs:
  update-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 192.168.87.185
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: whoami
               
          
            