name: Merging & Sending (Docker update and SSH.)

on:
  push:
    branches: ["main"]

jobs:
  update-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: 22
          key: ${{ secrets.SSH_KEY }}
          source: "/app/dist/*"
          target: "/var/www/"
