name: Merging & Sending (Docker update and SSH)

on:
  push:
    branches: ["main"]

jobs:
  update-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Copy files to remote server
        uses: appleboy/scp-action@master
        with:
          host: 192.168.87.185
          username: ubuntu
          password: ${{ secrets.DOCKER_PASS }}
          source: "test.yml"
          target: "/home/ubuntu"
