name: Merging & Sending (Docker update and SSH)

on:
  push:
    branches: ["main"]

jobs:
  update-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checks the action code from GitHub
        uses: actions/checkout@v2
      - name: Login to Docker Hub using username and pass
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and tag Docker image
        run: |
          docker build . -t kastholm/musikmekanikeren:test
          docker push kastholm/musikmekanikeren:test

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: 192.168.87.185
          username: ubuntu
          password: ${{ secrets.DOCKER_PASS }}
          port: 22
          source: "/app/dist/*"
          target: "/var/www/webtify.website/musikmekanikeren"
