name: Merging & Sending (Docker update and SSH)

on:
  push:
    branches: ["main"]

jobs:
  update-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checks the action code from GitHub
        uses: actions/checkout@v2
      - name: Login to Docker Hub using username and pass
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and tag Docker image
        run: |
          docker build . -t kastholm/musikmekanikeren:test
          docker push kastholm/musikmekanikeren:test
          docker restart b979fedd7d67616ffcac223c5b6da1613e9f2a185f6c6d9aeb85f961050ad6ee
