name: Merging & Sending (Docker update and SSH.)

on:
  push:
    branches: ["main"]

jobs:
  update-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.87.185
          username: root
          password: ${{ secrets.DOCKER_PASS }}
          script: |
            scp -r /app/dist/* root@192.168.87.185:/var/www/